### ISSUE TITLE
Confusing Typo 

### ISSUE THREAD

**Issue by Aexyn** [tslamic/tslamic.github.io#1]
Post: https://tslamic.github.io/android-menu-icon/
Line : Since h is of the same length as a square with an edge m, we deduct z=m
Correction: Since h is of the same length as "Diagonal of" a square with an edge m, we deduct z=m

**Comment by tslamic** [comment]
Hi Aexyn,

great catch, many thanks for reporting it! I’ll fix it as soon as I get home.

Cheers,
Tadej
